# Site settings
title: RZZT
homepage_title: Home
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rzzt.io" # the base hostname & protocol for your site
collections:
  minutes:
    output: true
  policies:
    output: true
  structural-documents:
    output: true
  register-of-interests:
    output: false
# Build settings
markdown: kramdown
