# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RZZT
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  RZZT CIC is a Community Interest Company incorporated in the United Kingdom and registered in England & Wales as a private company limited by guarantee. Its company number is 10951485, and its registered office is at International House, 776-778 Barking Road, Barking, London, E13 9PJ. More details are available at the Companies House website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rzzt.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: RZZT_CIC
github_username: RZZT
facebook_username: RZZTCIC

collections:
  terms-of-reference:
    output: true
  minutes:
    output: true
  policies:
    output: true
  forms:
    output: true
  balance-sheets:
    output: true
  profit-and-loss-statements:
    output: true

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
